export default {
  en: [
    [
      {label: '`', secondLabel: '~', keyCode: 'Backquote'},
      {label: '1', secondLabel: '!', keyCode: 'Digit1'},
      {label: '2', secondLabel: '@', keyCode: 'Digit2'},
      {label: '3', secondLabel: '#', keyCode: 'Digit3'},
      {label: '4', secondLabel: '$', keyCode: 'Digit4'},
      {label: '5', secondLabel: '%', keyCode: 'Digit5'},
      {label: '6', secondLabel: '^', keyCode: 'Digit6'},
      {label: '7', secondLabel: '&', keyCode: 'Digit7'},
      {label: '8', secondLabel: '*', keyCode: 'Digit8'},
      {label: '9', secondLabel: '(', keyCode: 'Digit9'},
      {label: '0', secondLabel: ')', keyCode: 'Digit0'},
      {label: '-', secondLabel: '_', keyCode: 'Minus'},
      {label: '=', secondLabel: '+', keyCode: 'Equal'},
      {label: '← Backspace', keyCode: 'Backspace'},
    ],
    [
      {label: 'Tab ⇄', keyCode: 'Tab'},
      {label: 'Q', keyCode: 'KeyQ', isСase: true},
      {label: 'W', keyCode: 'KeyW', isСase: true},
      {label: 'E', keyCode: 'KeyE', isСase: true},
      {label: 'R', keyCode: 'KeyR', isCase: true},
      {label: 'T', keyCode: 'KeyT', isCase: true},
      {label: 'Y', keyCode: 'KeyY', isCase: true},
      {label: 'U', keyCode: 'KeyU', isCase: true},
      {label: 'I', keyCode: 'KeyI', isCase: true},
      {label: 'O', keyCode: 'KeyO', isCase: true},
      {label: 'P', keyCode: 'KeyP', isCase: true},
      {label: '[', secondLabel: '{', keyCode: 'BracketLeft'},
      {label: ']', secondLabel: '}', keyCode: 'BracketRight'},
      {label: 'Delete', keyCode: 'Delete'},
    ],
    [
      {label: 'CapsLock', keyCode: 'CapsLock'},
      {label: 'A', keyCode: 'KeyA', isCase: true},
      {label: 'S', keyCode: 'KeyS', isCase: true},
      {label: 'D', keyCode: 'KeyD', isCase: true},
      {label: 'F', keyCode: 'KeyF', isCase: true},
      {label: 'G', keyCode: 'KeyG', isCase: true},
      {label: 'H', keyCode: 'KeyH', isCase: true},
      {label: 'J', keyCode: 'KeyJ', isCase: true},
      {label: 'K', keyCode: 'KeyK', isCase: true},
      {label: 'L', keyCode: 'KeyL', isCase: true},
      {label: ';', secondLabel: ':', keyCode: 'Semicolon'},
      {label: "'", secondLabel: '"', keyCode: 'Quote'},
      {label: 'Enter', keyCode: 'Enter'},
    ],
    [
      {label: 'Shift', keyCode: 'ShiftLeft'},
      {label: '\\', secondLabel: '|', keyCode: 'Backsla'},
      {label: 'Z', keyCode: 'KeyZ', isCase: true},
      {label: 'X', keyCode: 'KeyX', isCase: true},
      {label: 'C', keyCode: 'KeyC', isCase: true},
      {label: 'V', keyCode: 'KeyV', isCase: true},
      {label: 'B', keyCode: 'KeyB', isCase: true},
      {label: 'N', keyCode: 'KeyN', isCase: true},
      {label: 'M', keyCode: 'KeyM', isCase: true},
      {label: ',', secondLabel: '<', keyCode: 'Comma'},
      {label: '.', secondLabel: '>', keyCode: 'Period'},
      {label: '/', secondLabel: '?', keyCode: 'Slash'},
      {label: '↑', keyCode: 'ArrowUp'},
      {label: 'Shift', keyCode: 'ShiftRight'},
    ],
    [
      {label: 'Ctrl', keyCode: 'ControlLeft'},
      {label: '💻', keyCode: 'MetaLeft'},
      {label: '🌍', keyCode: 'ChangeLanguage'},
      {label: 'Alt', keyCode: 'AltLeft'},
      {label: '', keyCode: 'Space'},
      {label: 'Alt', keyCode: 'AltRight'},
      {label: 'Ctrl', keyCode: 'ControlRight'},
      {label: '←', keyCode: 'ArrowLeft'},
      {label: '↓', keyCode: 'ArrowDown'},
      {label: '→', keyCode: 'ArrowRight'},
    ],
  ],
  ru: [
    [
      {label: 'Ё', keyCode: 'Backquote'},
      {label: '1', secondLabel: '!', keyCode: 'Digit1'},
      {label: '2', secondLabel: '"', keyCode: 'Digit2'},
      {label: '3', secondLabel: '№', keyCode: 'Digit3'},
      {label: '4', secondLabel: ';', keyCode: 'Digit4'},
      {label: '5', secondLabel: '%', keyCode: 'Digit5'},
      {label: '6', secondLabel: ':', keyCode: 'Digit6'},
      {label: '7', secondLabel: '?', keyCode: 'Digit7'},
      {label: '8', secondLabel: '*', keyCode: 'Digit8'},
      {label: '9', secondLabel: '(', keyCode: 'Digit9'},
      {label: '0', secondLabel: ')', keyCode: 'Digit0'},
      {label: '-', secondLabel: '_', keyCode: 'Minus'},
      {label: '=', secondLabel: '+', keyCode: 'Equal'},
      {label: '← Backspace', keyCode: 'Backspace'},
    ],
    [
      {label: 'Tab ⇄', keyCode: 'Tab'},
      {label: 'Й', keyCode: 'KeyQ', isCase: true},
      {label: 'Ц', keyCode: 'KeyW', isCase: true},
      {label: 'У', keyCode: 'KeyE', isCase: true},
      {label: 'К', keyCode: 'KeyR', isCase: true},
      {label: 'Е', keyCode: 'KeyT', isCase: true},
      {label: 'Н', keyCode: 'KeyY', isCase: true},
      {label: 'Г', keyCode: 'KeyU', isCase: true},
      {label: 'Ш', keyCode: 'KeyI', isCase: true},
      {label: 'Щ', keyCode: 'KeyO', isCase: true},
      {label: 'З', keyCode: 'KeyP', isCase: true},
      {label: 'Х', keyCode: 'BracketLeft'},
      {label: 'Ъ', keyCode: 'BracketRight'},
      {label: 'Delete', keyCode: 'Delete'},
    ],
    [
      {label: 'CapsLock', keyCode: 'CapsLock'},
      {label: 'Ф', keyCode: 'KeyA', isCase: true},
      {label: 'Ы', keyCode: 'KeyS', isCase: true},
      {label: 'В', keyCode: 'KeyD', isCase: true},
      {label: 'А', keyCode: 'KeyF', isCase: true},
      {label: 'П', keyCode: 'KeyG', isCase: true},
      {label: 'Р', keyCode: 'KeyH', isCase: true},
      {label: 'О', keyCode: 'KeyJ', isCase: true},
      {label: 'Л', keyCode: 'KeyK', isCase: true},
      {label: 'Д', keyCode: 'KeyL', isCase: true},
      {label: 'Ж', keyCode: 'Semicolon'},
      {label: 'Э', keyCode: 'Quote'},
      {label: 'Enter', keyCode: 'Enter'},
    ],
    [
      {label: 'Shift', keyCode: 'ShiftLeft'},
      {label: '\\', secondLabel: '|', keyCode: 'Backslash'},
      {label: 'Я', keyCode: 'KeyZ', isCase: true},
      {label: 'Ч', keyCode: 'KeyX', isCase: true},
      {label: 'С', keyCode: 'KeyC', isCase: true},
      {label: 'М', keyCode: 'KeyV', isCase: true},
      {label: 'И', keyCode: 'KeyB', isCase: true},
      {label: 'Т', keyCode: 'KeyN', isCase: true},
      {label: 'Ь', keyCode: 'KeyM', isCase: true},
      {label: 'Б', keyCode: 'Comma'},
      {label: 'Ю', keyCode: 'Period'},
      {label: '.', secondLabel: ',', keyCode: 'Slash'},
      {label: '▲', keyCode: 'ArrowUp'},
      {label: 'Shift', keyCode: 'ShiftRight'},
    ],
    [
      {label: 'Ctrl', keyCode: 'ControlLeft'},
      {label: '💻', keyCode: 'MetaLeft'},
      {label: '🌍', keyCode: 'ChangeLanguage'},
      {label: 'Alt', keyCode: 'AltLeft'},
      {label: '', keyCode: 'Space', isWritable: true},
      {label: 'Alt', keyCode: 'AltRight'},
      {label: 'Ctrl', keyCode: 'ControlRight'},
      {label: '◀', keyCode: 'ArrowLeft', isWritable: true},
      {label: '▼', keyCode: 'ArrowDown', isWritable: true},
      {label: '▶', keyCode: 'ArrowRight', isWritable: true},
    ],
  ],
};